# Google Cloud Platform configuration
runtime: nodejs18

env_variables:
  NODE_ENV: production
  DB_HOST: /cloudsql/TU_PROJECT_ID:REGION:INSTANCE_NAME
  DB_NAME: BD_afirma
  DB_USER: postgres
  DB_PASSWORD: TU_PASSWORD_SEGURO
  INSTANCE_CONNECTION_NAME: TU_PROJECT_ID:REGION:INSTANCE_NAME

automatic_scaling:
  min_instances: 1
  max_instances: 10

handlers:
- url: /.*
  script: auto
  secure: always